CREATE TABLE `emailTracking` (
	`id` int AUTO_INCREMENT NOT NULL,
	`trackingId` varchar(64) NOT NULL,
	`emailType` enum('ANNIVERSARY_GREETING','ANNIVERSARY_REMINDER','POLICY_REVIEW_REMINDER','CHARGEBACK_ALERT','GENERAL_NOTIFICATION') NOT NULL,
	`recipientEmail` varchar(255) NOT NULL,
	`recipientName` varchar(255),
	`subject` varchar(500),
	`relatedEntityType` varchar(50),
	`relatedEntityId` varchar(100),
	`sentAt` timestamp,
	`sendStatus` enum('PENDING','SENT','FAILED','BOUNCED') DEFAULT 'PENDING',
	`sendError` text,
	`openedAt` timestamp,
	`openCount` int DEFAULT 0,
	`lastOpenedAt` timestamp,
	`clickedAt` timestamp,
	`clickCount` int DEFAULT 0,
	`lastClickedAt` timestamp,
	`clickedLinks` json,
	`lastUserAgent` varchar(500),
	`lastIpAddress` varchar(50),
	`metadata` json,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `emailTracking_id` PRIMARY KEY(`id`),
	CONSTRAINT `emailTracking_trackingId_unique` UNIQUE(`trackingId`)
);
